elimuinformatics/charts-on-fhir

- package-lock.json
- package.json
- projects/ngx-charts-on-fhir/src/lib/analysis/analysis-card/analysis-card.component.html
- projects/ngx-charts-on-fhir/src/lib/analysis/analysis.component.spec.ts
- projects/ngx-charts-on-fhir/src/lib/analysis/analysis.component.ts
- projects/ngx-charts-on-fhir/src/lib/analysis/analysis.module.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.spec.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-merge.service.spec.ts
- projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.spec.ts
- projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.ts
- projects/ngx-charts-on-fhir/src/lib/fhir-converter/fhir-converter.service.ts
- projects/ngx-charts-on-fhir/src/lib/fhir-mappers/component-observation-mapper.service.spec.ts
- projects/ngx-charts-on-fhir/src/lib/fhir-mappers/simple-observation-mapper.service.spec.ts
- Added unit tests for most services
- Added unit tests for the analysis component
- Fixed some bugs that I discovered while writing tests
Tested by running the unit tests and showcase app
> Colin prototype spec

- .github/workflows/build-test.js.yml
Adds workflow to build & test the library and showcase app
> Build and Test Workflow

- projects/ngx-charts-on-fhir/src/lib/data-layer-list/data-layer-list/data-layer-list.component.css
- projects/ngx-charts-on-fhir/src/lib/data-layer-list/data-layer-list/data-layer-list.component.html
- projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar-button/data-layer-toolbar-button.component.css
- projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar-button/data-layer-toolbar-button.component.html
- projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar-button/data-layer-toolbar-button.component.spec.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar-button/data-layer-toolbar-button.component.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar.module.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar/data-layer-toolbar.component.css
- projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar/data-layer-toolbar.component.html
- projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar/data-layer-toolbar.component.spec.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar/data-layer-toolbar.component.ts
- projects/ngx-charts-on-fhir/src/public-api.ts
- projects/showcase/src/app/app.component.html
- projects/showcase/src/app/app.component.scss
- projects/showcase/src/app/app.component.ts
- projects/showcase/src/app/app.module.ts
- projects/showcase/src/styles.scss
Showcase app:
- Moved data-layer-list into the sidenav
- Added data-layer-toolbar
Library:
- Created data-layer-toolbar module and components
- Fixed data-layer-list scrolling when displayed inside sidenav
Ran showcase app, added some layers, clicked toolbar buttons and close button
> Hide layer options

- projects/ngx-charts-on-fhir/src/lib/analysis-cards/statistics/statistics.component.css
- projects/ngx-charts-on-fhir/src/lib/analysis-cards/statistics/statistics.component.html
- projects/ngx-charts-on-fhir/src/lib/analysis-cards/statistics/statistics.component.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.component.html
- projects/ngx-charts-on-fhir/src/lib/data-layer-list/data-layer-list/data-layer-list.component.css
- projects/ngx-charts-on-fhir/src/lib/data-layer-list/data-layer-options/data-layer-options.component.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.spec.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer.ts
- projects/showcase/src/app/cards/custom-card-example/custom-card-example.component.ts
Fixes bugs and code smells identified by sonar scan:
- Add aria-label to tables
- Use `th scope=row` instead of td for first column of statistics table (required some custom styles)
- Removed unused imports and empty css files
Ran the showcase app and looked at the tables
> Fix sonar issues

- projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.component.css
- projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.component.html
- projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.component.spec.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.component.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.module.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.ts
Added a simple progress bar for layer loading, it shows until all layer is loaded and then after loading all layer it will hide  
Tested on local
> RT-507:Loading indicators

- projects/ngx-charts-on-fhir/src/lib/data-layer-list/annotation-list/annotation-list.component.spec.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer-list/data-layer-list.module.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer-list/data-layer-options/data-layer-options.component.spec.ts
Fixed the Annotation test errors
Tested by run unit test cases on local
> RT-553:Annotation test errors

- projects/ngx-charts-on-fhir/src/lib/data-layer-list/annotation-options/annotation-options.component.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-color.service.spec.ts
- projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-color.service.ts
Fixed the issue 
Tested on local by running app on local.
> RT-552:Annotation options displays the wrong color

- projects/ngx-charts-on-fhir/src/lib/fhir-chart/range-selector/range-selector.component.ts
Call Service for getting Maximum and Minimum values from the visible data layer.
Also, convert this timestamp value into a date and set it to maxDate and MinDate.
Test the code using the run showcase app locally.
> RT-573:Date of timespan should change on when we manually zoom in chart

- projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.html
- projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.ts
- Update chart height to compensate for range selector
- Ran showcase app
> Fix chart height

- projects/ngx-charts-on-fhir/src/lib/fhir-chart/range-selector/range-selector.component.ts
Check whether the value of the X axis is a number or not and then filter the layer data.
tested using the run showcase app locally and add observation and then add medication.
> RT-575:End Date does not work for medications

- projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.component.html
remove the progress bar after completing the data load
> RT-578:Progress bar empty space

- projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.spec.ts
- My previous PR #44 had some disabled/unfinished unit tests
- This PR fixes those tests and enables them
- Ran unit tests
> timelineRange unit tests

- projects/cardiovascular-health/src/test.ts
update cardiovascular-health test.ts file.
Tested using run showcase app & cardiovascular-health app.
> RT-590:Build is faling when added cardiovascular-health in workplace

- projects/ngx-charts-on-fhir/src/lib/data-layer-list/annotation-list/annotation-list.component.html
remove the annotation option header from the annotation list
> RT-589-remove-annotation-option

- projects/ngx-charts-on-fhir/src/lib/data-layer-list/dataset-options/dataset-options.component.html
Removed bar chart option from dataset-option-component.html
Tested locally by launching showcase app.
> RT-598 Remove bar chart option

- projects/ngx-charts-on-fhir/src/lib/data-layer-list/dataset-options/dataset-options.component.html
- projects/ngx-charts-on-fhir/src/lib/data-layer-list/dataset-options/dataset-options.component.ts
Add ngIf condition for checking dataset.yAxisID is medication or not.
Also, change the private _dataset to  _dataset. 
Ran Showcase App locally.
> RT-597-medication-option

- projects/showcase/src/app/providers/palette-provider.ts
Changed the red color to light red and the yellow color to dark yellow in the color palette.
Tested it by launching a showcase locally.
> RT-599-Adjust-color-palette

- projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/medication-summary.service.spec.ts
- projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/medication-summary.service.ts
change “Date Written” column heading instead of “Authored On” in the medication summary.
> RT-616-Medication-Date:Medication-Date Written

- projects/cardiovascular-health/src/app/providers/summary-providers.ts
Add MedicationSummaryService in summary-provider.
Tested Using Run cardio-health app locally.
> RT-615-Medication-Summary

- projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.ts
- projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/fhir-chart-summary/fhir-chart-summary.component.html
- projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/fhir-chart-summary/fhir-chart-summary.component.spec.ts
- projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/fhir-chart-summary/fhir-chart-summary.component.ts
Add the ngIf condition to check layer is enabled or not.
> RT-633-Summary-Card:Summary Card is not removed for disabled layers

- projects/cardiovascular-health/src/app/providers/summary-providers.ts
- projects/cardiovascular-patient-app/src/app/providers/summary-providers.ts
- projects/ngx-charts-on-fhir/src/public-api.ts
- projects/showcase/src/app/providers/summary-providers.ts
- Added it to public-api
- Added it to cardio clinician and patient apps
- Fixed import path in showcase app
- Ran showcase app with mock FHIR server and checked that home measurements display correctly
- Regression tested cardio apps, but I do not yet have home measurement data in Logica.
> HomeMeasurementSummaryService export/imports

- projects/cardiovascular-health/src/app/providers/palette-provider.ts
- projects/cardiovascular-patient-app/src/app/providers/palette-provider.ts
- projects/showcase/src/app/providers/palette-provider.ts
- Removed yellow, light yellow, and light purple from color palette for all apps
- Updated cardio and cardio-patient apps with some prior color changes that were only made to showcase
- Ran showcase and cardio apps
- Checked colors in color picker and line graphs
> Remove hard-to-see colors

- projects/cardiovascular-patient-app/src/launch.html
- Added launch.html to patient app
- Created Patient Persona in Logica Sandbox
- Created Launch Scenario for localhost
- Launched patient app from Logica using localhost launch scenario
> SMART launch for Patient app

- projects/ngx-charts-on-fhir/src/lib/utils.spec.ts
- projects/ngx-charts-on-fhir/src/lib/utils.ts
Updated unit test case of formatTime function for different time zones.
Ran unit test locally and Ran unit test on different timezone
> RT-661-Unit-test-failing: updated formatTime function

- projects/cardiovascular-patient-app/src/app/app.component.html
- projects/cardiovascular-patient-app/src/app/app.component.spec.ts
- projects/cardiovascular-patient-app/src/app/app.component.ts
- projects/cardiovascular-patient-app/src/app/report-bp/report-bp.component.spec.ts
- projects/cardiovascular-patient-app/src/app/report-bp/report-bp.component.ts
Use @output decorator and EventEmitter to emit the event.
After the form submit emit the event and pass selectedIndex for the tab is equal to 1.
Tested Using run cardio-patient-app locally.
> RT-657-Change-tab

- projects/ngx-charts-on-fhir/src/lib/fhir-data/fhir-data.service.ts
Change createBloodPressureResource and add a (Home) extension in the label and Text.
Run the cardio-patient app locally.
post the data and check in fhir-chart.
> RT-656:Use measurement setting in patient app

- .github/workflows/build-test.js.yml
- angular.json
- Increased bundle budget for documentation project
- Rewrote GitHub Workflow to split up build job and run some things in parallel
- Added publish-docs job to GitHub Workflow
- Tested documentation build locally
> Publish documentation

- .github/workflows/build-test.js.yml
- Added deploy-docs job to deploy the documentation to github pages
- Cannot test until this PR is merged
> Deploy documentation

- projects/cardiovascular-patient-app/src/app/datasets/observations.service.ts
Change the final URL for getPatientData.
Sort the patient Data using date.
change the FHIR query so it retrieves the most recent data first.
Tested Using launch cardio-patient-app locally using logica.
> RT-672-last-reported-BP-changes:Last reported BP changes as data is loaded

- projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/statistics.service.spec.ts
- projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/statistics.service.ts
- projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.spec.ts
- projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.ts
Add a custom tooltip plugin for showing the reference range.
Tested using run showcase,cardio-patient, and cardio-health app locally.
> RT:678_reference range tooltip

- projects/ngx-charts-on-fhir/package.json
- bump version to 1.1.0
- not tested
> Bump version to 1.1.0

- projects/cardiovascular-patient-app/src/app/report-bp/report-bp.component.spec.ts
- projects/cardiovascular-patient-app/src/app/report-bp/report-bp.component.ts
Remove dots and exclamation points from the success and error messages after submitting BP data.
Also, updated the test cases according to the changes.
Tested using run `cardio-patient-app` locally.
> RT-698-Clean-up-messages:Clean up success/error messages

- package-lock.json
-Fixed vulnerabilities in charts-on-fhir
-Tested it by build chart-on-fhir library on local and launched showcase, cardio-patient, cardio-health on local.
-Ran unit test locally.
> RT-694-Fix-vulnerabilities-json5

- libs/ngx-charts-on-fhir/package.json
> Bump version to 1.2.0

- libs/ngx-charts-on-fhir/package.json
- package-lock.json
- package.json
- Update the `@types/fhir` version 0.0.35 to 0.0.37.
- Not tested locally.
> RT-843-Update-@types/fhir-dependency-to latest version in charts-on-fhir

- libs/ngx-charts-on-fhir/package.json
- Update the `@elimuinformatics/ngx-charts-on-fhir` version 2.0.0 to 2.1.0 .
- Tested locally.
> RT-845-Update-@elimuinformatics/ngx-charts-on-fhir-npm-package-version

- libs/ngx-charts-on-fhir/package.json
> bump version number to 2.1.1

- libs/ngx-charts-on-fhir/src/lib/timeline-range-selector/timeline-range-selector.component.css
- Added flex-wrap:wrap style on range-selector-buttons component.
- Tested using run showcase app locally.
> RT-872-Fix-Width-Issue-in-time-Range-Selector-buttons

- libs/ngx-charts-on-fhir/package.json
- Update the @elimuinformatics/ngx-charts-on-fhir version  2.1.1 to 2.1.2.
> RT-874-Update-@elimuinformatics/ngx-charts-on-fhir-version

- libs/ngx-charts-on-fhir/package.json
Publish new version 2.1.3 of chart-on-fhir. 
Tested on local.
> RT-878:Remove "timeline view" from range-selector component, Publish new version 2.1.3 of chart-on-fhir 

- apps/cardiovascular-health/src/app/app.component.html
- apps/cardiovascular-health/src/app/app.module.ts
- apps/showcase/src/app/app.component.html
- apps/showcase/src/app/app.module.ts
- libs/ngx-charts-on-fhir/package.json
- libs/ngx-charts-on-fhir/src/lib/timeline-range-selector/timeline-range-selector.component.html
- libs/ngx-charts-on-fhir/src/lib/timeline-range-selector/timeline-range-selector.component.ts
Added an option to show and hide a timeline view title.
Tested by running showcase, cardiovascular-health and cardiovascular-patient-app apps on locally.
> RT-884:gap under timeline view label

- libs/ngx-charts-on-fhir/package.json
- Update @elimuinformatics/ngx-charts-on-fhir version 3.1.0 to 3.1.1
- Tested locally using run all `charts-on-fhir` apps.
> RT-912-Update-@elimuinformatics/ngx-charts-on-fhir-version

- libs/ngx-charts-on-fhir/package.json
- bump version number to 3.2.0
- N/A
> bump version to 3.2.0

- Jenkinsfile
- Write the Jenkins file for QA env.
- Validate with Jenkins Pipeline Linter Connector.
> RT-942-Migrate-charts-on-fhir-jobs-to-new-Jenkins-server

- libs/ngx-charts-on-fhir/package.json
- Version updated 3.2.1 to 3.2.2.
- Tested locally using run charts-on-fhir app.
- [ X] I have added a link to this PR in the Jira issue
- [ X] I have described how this was tested
> RT-1116-Version updated 3.2.1 to 3.2.2

- libs/ngx-charts-on-fhir/package.json
- Updated the version from 3.2.2 to 3.2.3
- Tested by launching charts-on-fhir app locally
> RT-1116: Updated the version from 3.2.2 to 3.2.3

- .github/workflows/release.yml
- Updates versions of github pages actions to fix deployment error in Release workflow
- Temporarily changed the workflow to run the deployment from this PR
> Fix documentation deployment workflow

- libs/ngx-charts-on-fhir/src/lib/provide-charts-on-fhir.spec.ts
- Removed `f` so all tests will run
- Ran tests locally
> remove test focus

- libs/ngx-charts-on-fhir/src/lib/fhir-mappers/fhir-mapper-options.ts
- Exports the default mapper options to make them easier to customize
- Ran unit tests
> Export default mapper options

- libs/ngx-charts-on-fhir/package.json
- bump version number to 3.4.0
N/A
> bump version to 3.4.0

- libs/ngx-charts-on-fhir/package.json
- libs/ngx-charts-on-fhir/src/lib/fhir-mappers/encounter/encounter-mapper.service.ts
- libs/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/simple-medication-mapper.service.ts
- Updated the medication and encounter mapper to update labels text color
- Tested by launching the charts-on-fhir showcase app, and verified labels are showing as expected.
> Updated the medication and encounter mapper to update labels text color

- libs/ngx-charts-on-fhir/package.json
- Updated charts-on-fhir version from 3.4.4 to 3.4.5
> Update charts-on-fhir version to 3.4.5

- Dockerfile
- apps/cardio-patient/project.json
- apps/cardio-patient/tsconfig.json
- apps/cardio/project.json
- apps/cardio/tsconfig.json
- apps/documentation/project.json
- apps/documentation/src/styles.scss
- apps/documentation/tsconfig.json
- apps/showcase/project.json
- apps/showcase/tsconfig.json
- libs/ngx-charts-on-fhir/package.json
- libs/ngx-charts-on-fhir/src/default-fonts.scss
Run nx migration to Update to new angular builder for all the chart on fhir projects,
Updated a docker. 
I tested all chart on fhir projects locally.
- [X ] I have added a link to this PR in the Jira issue
- [X ] I have described how this was tested
> RT-1513:(charts-on-fhir) Update to new angular builder

- libs/ngx-charts-on-fhir/package.json
- libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.ts
Adjust the mapper to works correctly with the less restrictive type simpleObservationmapper.
Tested by running showcase app
> RT-1614   (mme) Pain Score Timeline

- libs/ngx-charts-on-fhir/package.json
- libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.spec.ts
- libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.ts
update simple observation mapper for pain score timeline
Tested by adding same code in mme pain score mapper.
- [X ] I have added a link to this PR in the Jira issue
- [X ] I have described how this was tested
- [X ] I have included screen shots for changes that affect the user interface
> RT-1614 update simple observation mapper for pain score timeline

- libs/ngx-charts-on-fhir/package.json
- bumped version to 6.1.0
- not tested
> bumped version to 6.1.0

- libs/ngx-charts-on-fhir/package.json
- libs/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/simple-medication-mapper.service.spec.ts
- libs/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/simple-medication-mapper.service.ts
- Updated plugin to ignore datasets with no data
- Tested by using charts-on-fhir package locally with sapphire.
- Tested by running unit tests .
> Fix runtime error in medication mapper when data array is empty

- libs/ngx-charts-on-fhir/package.json
- libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.spec.ts
- libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.ts
- libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.spec.ts
- libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.ts
Enhance observation mapping to support effectiveInstant and effectivePeriod.start
Added unit test cases
Launching showcase app with mock data
Also, test connecting charts-on-fhir to sapphire
Sapphire screenshot with patient id **empty**
> Enhance observation mapping to support effectiveInstant and effectivePeriod.start

- libs/ngx-charts-on-fhir/package.json
- libs/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/duration-medication-mapper.service.spec.ts
- libs/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/duration-medication-mapper.service.ts
- Add validation for BoundsPeriodMedication duration to ensure it is at least 24 hours.
- Added test case.
- Tested with mock data.
- Tested by running unit tests.
> Validate BoundsPeriod duration to be greater than 24hr

- Dockerfile
- libs/ngx-charts-on-fhir/package.json
- libs/ngx-charts-on-fhir/test-npm-package.Dockerfile
- package-lock.json
- Updated library dependencies to Angular version 19.
- Bump ngx-charts-on-fhir version to 7.0.2
- Tested by launching showcase application locally with mock data.
- Tested by running unit tests.
> Update library dependencies to Angular 19

- libs/ngx-charts-on-fhir/package-lock.json
- package-lock.json
- package.json
- Fixed vulnerabilities
- Tested by running documentation app.
> Fix vulnerabilities

- libs/ngx-charts-on-fhir/package.json
- libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.ts
-  Improves the tooltip title handling in chart tooltips by ensuring unique titles.
- Tested locally with mock data.
- Tested by running unit tests.
> Improve tooltip title uniqueness.

- libs/ngx-charts-on-fhir/package.json
- libs/ngx-charts-on-fhir/src/lib/summary-range-selector/summary-range-selector.component.scss
- libs/ngx-charts-on-fhir/src/lib/summary-range-selector/summary-range-selector.component.ts
- libs/ngx-charts-on-fhir/src/lib/timeline-range-selector/timeline-range-selector.component.html
- libs/ngx-charts-on-fhir/src/lib/timeline-range-selector/timeline-range-selector.component.scss
- libs/ngx-charts-on-fhir/src/lib/timeline-range-selector/timeline-range-selector.component.ts
- Improved the appearance of Timeline Range Selector component
- Switched to outlined form field and reduced the height of button toggle
- Ran showcase app and documentation app.
> Range selector UI update
