elimuinformatics/charts-on-fhir

angular.json

Increased initial budget error threshold to 1.5mb so the build will succeed.
We should review the budget again after we implement lazy-loading.

Increase showcase bundle budget

---

projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.css
projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.html
projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.ts
projects/showcase/src/app/app.component.html

- Added `width` and `height` inputs to fhir-chart component
- Fixed centering of the empty chart message
- Disabled the chart.js `maintainAspectRatio` option
- Updated showcase app set the width/height

Configurable chart size

---

.github/workflows/build-test.js.yml

Added `sonar.coverage.exclusions` and `sonar.test.inclusions` parameters so SonarCloud scan will calculate test coverage correctly.
I can't find a way to view the sonar code coverage report for this PR. I will test it by merging the PR so the updated workflow runs on main.

Exclude tests and angular files from test coverage

---

projects/showcase/src/app/app.component.html
projects/showcase/src/app/app.component.ts

Use sidenav's autosize property instead of close and re-open, which was causing animation glitches.
Ran showcase app, added layers with long names, switched sidenav panels back and forth to check resizing.

use sidenav autosize

---

projects/ngx-charts-on-fhir/src/lib/data-layer-list/data-layer-list/data-layer-list.component.html
projects/ngx-charts-on-fhir/src/lib/data-layer-list/data-layer-options/data-layer-options.component.html
projects/ngx-charts-on-fhir/src/lib/data-layer-list/data-layer-options/data-layer-options.component.ts
projects/ngx-charts-on-fhir/src/lib/data-layer-list/dataset-list/dataset-list.component.html
projects/ngx-charts-on-fhir/src/lib/data-layer-list/dataset-list/dataset-list.component.ts
projects/ngx-charts-on-fhir/src/lib/data-layer-list/dataset-options/dataset-options.component.ts
projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar/data-layer-toolbar.component.ts
projects/showcase/src/app/app.component.html

Some components had `@Output()` events named “change”. This collided with a built-in event name for input elements, resulting in the event handler getting called unexpectedly when the input change event bubbled up.
This PR changes all of those outputs to use more specific names.
Ran the app locally and triggered all of the changed events in the UI.

Fix event names

---

projects/ngx-charts-on-fhir/src/lib/analysis-cards/analysis-utils.spec.ts
projects/ngx-charts-on-fhir/src/lib/data-layer/visible-data.service.ts
projects/ngx-charts-on-fhir/src/lib/data-layer/visible-data.spec.ts
projects/ngx-charts-on-fhir/src/lib/utils.ts

- Resolves logical conflicts between medication and chart summary branches.
- `VisibleDataService` now filters out string y-values so `$visible.data` only contains valid `ScatterDataPoint`s
- Statistics panel does not really make sense for medications. It currently displays N/A or NaN for most rows. I will open a new issue for that. This PR only fixes the build errors.
Added some medications and observations to the chart

Fix build errors for medication summary

---

projects/ngx-charts-on-fhir/src/lib/data-layer-list/annotation-list/annotation-list.component.html
projects/ngx-charts-on-fhir/src/lib/data-layer-list/annotation-list/annotation-list.component.spec.ts
projects/ngx-charts-on-fhir/src/lib/data-layer-list/annotation-list/annotation-list.component.ts
projects/ngx-charts-on-fhir/src/lib/data-layer-list/annotation-options/annotation-options.component.spec.ts
projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-color.service.spec.ts
projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-color.service.ts

- Fixed annotation checkbox disables the wrong annotation issue.
- Tested it by launching charts-on-fhir locally.
- Ran unit test cases locally.

RT-549 Annotation checkbox disables the wrong annotation

---

projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.component.css
projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.component.html
projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.component.spec.ts
projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.component.ts
projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.module.ts
projects/ngx-charts-on-fhir/src/lib/data-layer-list/data-layer-options/data-layer-options.component.spec.ts
projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.ts
projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer.ts
projects/ngx-charts-on-fhir/src/lib/fhir-converter/fhir-converter.service.ts
projects/ngx-charts-on-fhir/src/lib/fhir-mappers/component-observation-mapper.service.spec.ts
projects/ngx-charts-on-fhir/src/lib/fhir-mappers/component-observation-mapper.service.ts
projects/ngx-charts-on-fhir/src/lib/fhir-mappers/fhir-mapper-options.ts
projects/ngx-charts-on-fhir/src/lib/fhir-mappers/fhir-mappers.module.ts
projects/ngx-charts-on-fhir/src/lib/fhir-mappers/simple-medication-mapper.service.spec.ts
projects/ngx-charts-on-fhir/src/lib/fhir-mappers/simple-medication-mapper.service.ts
projects/ngx-charts-on-fhir/src/lib/fhir-mappers/simple-observation-mapper.service.spec.ts
projects/ngx-charts-on-fhir/src/lib/fhir-mappers/simple-observation-mapper.service.ts
projects/showcase/src/app/datasets/blood-pressure-mapper.ts
projects/showcase/src/app/datasets/fhir-data.service.spec.ts
projects/showcase/src/app/datasets/fhir-data.service.ts
projects/showcase/src/app/datasets/medications.service.ts
projects/showcase/src/app/providers/data-layer-providers.ts
projects/showcase/src/app/providers/mapper-providers.ts

- Changes the Showcase app to use a Logica Sandbox open API endpoint that I created for this project.
- Changes all code to support FHIR R4 instead of DSTU2:
- `Observation` can have multiple categories
- `MedicationOrder` -> `MedicationRequest`
- `dateWritten` -> `authoredOn`
- Tested with 3 different patients that I imported into the Logica Sandbox.
- Added some Observations and Medications to the chart
- Ran unit tests

FHIR R4 Logica Sandbox

---

projects/ngx-charts-on-fhir/src/lib/analysis-cards/analysis-card/analysis-card.component.css
projects/ngx-charts-on-fhir/src/lib/analysis-cards/analysis-card/analysis-card.component.html
projects/ngx-charts-on-fhir/src/lib/analysis-cards/analysis-cards.module.ts
projects/ngx-charts-on-fhir/src/lib/data-layer-list/data-layer-list.module.ts
projects/ngx-charts-on-fhir/src/lib/data-layer-list/data-layer-list/data-layer-list.component.css
projects/ngx-charts-on-fhir/src/lib/data-layer-list/data-layer-list/data-layer-list.component.html
projects/ngx-charts-on-fhir/src/lib/data-layer-list/dataset-list/dataset-list.component.css
projects/ngx-charts-on-fhir/src/lib/data-layer-list/dataset-list/dataset-list.component.html

Add ellipses on the Dataset Label, and layer name.
Also, Add a hover tooltip on the dataset label, layer name, and summary card title.

RT-554:Summary card title is too long

---

projects/ngx-charts-on-fhir/src/lib/fhir-mappers/fhir-mapper-options.ts

- Offset medication gridlines so they show in between bars instead of centered
- Move medication labels slightly closer to the bars
- Ran showcase app

Offset medication gridlines

---

angular.json
projects/ngx-charts-on-fhir/ng-package.json
projects/ngx-charts-on-fhir/package.json
projects/ngx-charts-on-fhir/src/default.scss
projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.component.css
projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.component.html
projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.component.ts
projects/ngx-charts-on-fhir/src/lib/data-layer-list/data-layer-list/data-layer-list.component.html
projects/ngx-charts-on-fhir/src/lib/data-layer-list/dataset-options/dataset-options.component.css
projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/_data-layer-toolbar-theme.scss
projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar-button/data-layer-toolbar-button.component.css
projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar/data-layer-toolbar.component.css
projects/ngx-charts-on-fhir/src/lib/dynamic-table/dynamic-table.component.css

- ngx-charts-on-fhir exports a `default.scss` material theme with increased density settings
- showcase app loads the theme in angular.json styles array
- applied the theme color to data-layer-toolbar component instead of using hardcoded indigo color
- replaced mini-fab buttons with smaller icon buttons in data-layer-browser (add) and data-layer-list (delete)
- improved data-layer-browser layout
- fixed some things from the material mdc migration and other minor style issues
- Ran showcase app with mock FHIR server

Add default theme with increased density

---

.github/workflows/build-test.js.yml

- Adds deploy job to build-test workflow
- deploy job only runs for main branch
- deploy job only runs after successful build/test/scan
- Tested that deployment is skipped for feature branches by checking the workflow results on this PR
- Cannot test deployment on main until this is merged

Add deployment to build-test workflow

---

projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.component.html

Added colspan to display empty messages properly
Tested by launching the charts-on-fhir locally, In the browser layer selected all layers and also search for layers that are not present in all layers. The empty message is showing properly after this change. Added The screenshot after colspan change.

RT-606-matNoDataRow-colspan

---

projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.component.css
projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.component.html
projects/ngx-charts-on-fhir/src/lib/data-layer-browser/data-layer-browser.module.ts
projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar-loading-indicator/data-layer-toolbar-loading-indicator.component.css
projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar-loading-indicator/data-layer-toolbar-loading-indicator.component.html
projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar-loading-indicator/data-layer-toolbar-loading-indicator.component.spec.ts
projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar-loading-indicator/data-layer-toolbar-loading-indicator.component.ts
projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar.module.ts
projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar/data-layer-toolbar.component.css
projects/ngx-charts-on-fhir/src/lib/data-layer-toolbar/data-layer-toolbar/data-layer-toolbar.component.html
projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.ts
projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.html
projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.ts
projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.module.ts

- Added loading message and progress bar to chart component. It is only displayed when chart is empty.
- Added loading indicator / done icon to toolbar. This indicator shows that data is still loading even if some of it is already displayed on the chart.
- Removed loading indicator from data-layer-browser. No longer needed now that we have one on the toolbar.
- Ran showcase and cardio apps with Logica
- Reloaded the page repeatedly and made sure loading indicators look good and are shown/hidden at the correct times.

Loading indicators

---

projects/cardiovascular-health/src/app/datasets/observations.service.ts

- Added LOINC code 2339-0 to cardio app's observations service so Synthea's Glucose measurements will show up in the app.
- Ran cardio app locally using a Patient with Glucose observations coded as 2339-0
- Checked that the Glucose graph is displayed

Add glucose code 2339-0

---

projects/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/blood-pressure-mapper.service.ts

Change Systolic yMax value from 130 to 140 and diastolic yMax from 80 to 90.
Tested Using run showcase app locally.

RT-632-BP-Range:Default BP Reference Range

---

projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-color.service.ts
projects/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/duration-medication-mapper.service.ts
projects/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.ts
projects/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.ts

- Sets a different point style/radius for home measurements
- Matches dataset and annotation colors by default
- Ran showcase app with home measurement data
- Tested that both home and office points display correctly
- Tested manually changing options as well

Default styles for home measurements

---

projects/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.spec.ts
projects/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.ts
projects/synthea-utils/index.ts

- Fixed location of measurement setting extension (`resource.extension` instead of `resource.meta.extension`) in synthea-utils script and observation mapper.
- Generated a patient with synthea-utils
- Checked the FHIR JSON bundle to make sure extension was correct
- Uploaded patient bundle to Logica
- Ran showcase app with Logica open FHIR server
- Checked that home/office measurements are displayed correctly

Fix measurement setting extension

---

projects/cardiovascular-health/src/app/app.component.ts
projects/cardiovascular-health/src/environments/environment.logica-open.ts

- Wait until data is done loading before selecting layers
- This is a temporary fix so colors will display correctly
- I will create a separate ticket to investigate the root cause and fix the services
- This also changes the logica open environment's default patient to one that has home measurements
- Did a local merge with #98 and ran Cardio app with Logica Open
- Tested a patient with Home measurements and checked that colors display correctly
- There is a slightly longer delay before data is shown, but this is acceptable for now. Will revisit this later.

Cardiovascular Health dataset colors

---

projects/ngx-charts-on-fhir/src/lib/data-layer-list/dataset-options/dataset-options.component.spec.ts
projects/ngx-charts-on-fhir/src/lib/data-layer-list/dataset-options/dataset-options.component.ts
projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-color.service.spec.ts
projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-color.service.ts
projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-merge.service.spec.ts
projects/ngx-charts-on-fhir/src/lib/data-layer/data-layer-merge.service.ts

- `DataLayerMergeService` now calls `colorService.chooseColorsFromPalette()` when adding a new dataset to a selected layer.
- Reworks the `chooseColorsFromPalette` code so it is more robust and works regardless of the order in which datasets are added.
- Fixes a bug in dataset-options component that was setting dataset color to empty string.
- Adds unit tests
- Ran cardiovascular-health app with Logica Open environment using patient 30049
- Temporarily changed cardio app.component so it calls `layerManager.select()` every time `availableLayers$` emits (I am not committing this change because we are rewriting that code in another PR and don't want conflicts)
- Checked that colors show up correctly while the graph is loading and after it finishes loading.
- Checked that colors show up …

Color service fixes

---

projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/home-measurement-summary.service.spec.ts
projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/home-measurement-summary.service.ts

- Fixes a bug where "Days Outside Goal" is not displayed in the summary panel for datasets with home measurements
- Ran cardio and showcase apps locally with Logica Open environment, Patient 30049
- Checked that Outside Goal is displayed in the BP summary panel

Fix Days Outside Goal is not displayed

---

projects/ngx-charts-on-fhir/src/lib/fhir-data/fhir-data.service.ts

- Removed imports from `fhirclient/lib`, which were causing mysterious webpack errors about nodejs 'http' module when the library was used with rxjs 7.6+
- Ran prettier on fhir-data.service.ts
- Updated rxjs to 7.6, built ngx-charts-on-fhir, and ran showcase app
- This causes a build error on main but not on this feature branch.

Fix: Cannot find module 'http'

---

projects/cardiovascular-patient-app/src/app/app.component.html
projects/cardiovascular-patient-app/src/app/app.component.ts

For getting Updated BP layer data we call the retrieveAll function.
Tested using run cardio-patient-app locally.

RT-659-Refresh-chart:Refresh chart and last-reported after submitting BP

---

projects/cardiovascular-patient-app/src/app/last-report-bp/last-report-bp.component.html
projects/cardiovascular-patient-app/src/app/last-report-bp/last-report-bp.component.ts
projects/cardiovascular-patient-app/src/app/last-report-bp/last-report-bp.module.ts

Used the ngIf condition for checking layermanger.loading or not.
A mat-progress-bar  and Loading data text are used to indicate that data is being loaded, and after loading, the message is displayed.
Tested Using Run cardio-patient-app locally.

RT-663-loading-indicator:Patient app loading indicator

---

.github/workflows/npm-publish.yml

- Added a GitHub workflow to publish package to NPM when a GitHub Release is published.
- Cannot test until we publish a release.

NPM publish workflow

---

.github/workflows/npm-publish.yml

- Added dir to npm publish command instead of trying to `cd` in a separate step
- Ran npm publish command locally with --dry-run to make sure it packages the right dir

Fix npm publish dir

---

.github/workflows/npm-publish.yml

According to [this post](https://github.com/npm/cli/issues/3993), adding a trailing slash should fix this workflow failure.
- N/A

Add trailing slash to npm publish dir

---

.github/workflows/build-test.js.yml

- Set base-href to /charts-on-fhir/ when building docs for github-pages
- Cannot test until it is merged

Set base-href when building docs for github-pages

---

.github/workflows/build-test.js.yml

- Copy index.html to 404.html so requests will go to Angular router instead of GitHub's 404 page
- Not tested (cannot publish from PR due to protection rules for github pages environment)

Fix Angular routing in GitHub Pages

---

projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/fhir-chart-summary-card/fhir-chart-summary-card.component.css
projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/fhir-chart-summary-card/fhir-chart-summary-card.component.html
projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/medication-summary.service.spec.ts
projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/medication-summary.service.ts
projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/summary.service.spec.ts
projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/summary.service.ts

-Replaced the “name” column heading with the dataset label in the summary card. 
-Remove the mat-card and used a simple card.
-Tested showcase,cardio-patient, and cardio-health locally.
ntent.com/57406228/225916081-39ffa151-ca74-4cef-869a
-ac3ec8dcd346.png)

RT-683-Rework-summary-card-layout

---

projects/cardiovascular-health/src/app/app.component.html
projects/cardiovascular-patient-app/src/app/app.component.html
projects/cardiovascular-patient-app/src/app/app.component.spec.ts
projects/cardiovascular-patient-app/src/app/app.module.ts
projects/cardiovascular-patient-app/src/app/options-menu/options-menu.component.html
projects/cardiovascular-patient-app/src/app/options-menu/options-menu.component.spec.ts
projects/cardiovascular-patient-app/src/app/options-menu/options-menu.component.ts
projects/cardiovascular-patient-app/src/app/options-menu/options-menu.module.ts
projects/ngx-charts-on-fhir/src/lib/fhir-chart-legend/fhir-chart-legend.component.css
projects/ngx-charts-on-fhir/src/lib/fhir-chart-legend/fhir-chart-legend.component.html
projects/ngx-charts-on-fhir/src/lib/fhir-chart-legend/fhir-chart-legend.component.spec.ts
projects/ngx-charts-on-fhir/src/lib/fhir-chart-legend/fhir-chart-legend.component.ts
projects/ngx-charts-on-fhir/src/lib/fhir-chart-legend/fhir-chart-legend.module.ts
projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.css
projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.html
projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.ts
projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.module.ts
projects/showcase/src/app/app.component.html

ngx-charts-on-fhir:
- Replaces the chart.js legend with a custom legend component
- Legend component can be placed at the top, bottom, or floating (`legendPosition` input on fhir-chart component)
- Floating legend can be moved around by dragging it
- Legend shows the correct colors and symbols for symbols that can be set via dataset-options component
- If an app programmatically assigns an unsupported symbol, it will show up as a square in the legend
cardiovascular-patient-app:
- Legend is hidden by default
- Added a menu to the toolbar for toggling the legend
showcase & cardiovascular-health:
- Legend is displayed at the top of the chart
- Ran showcase, cardio, and patient apps
- Tested all different screen sizes to make sure legend displays correctly

Custom Legend

---

karma.base.conf.js

Set `failSpecWithNoExpectations` true in karma.base.conf file.
Tested using run test cases without except() for all charts-on-fhir apps.

RT-689-fail-specs-with-no-expectations:Jasmine should fail specs with no expectations

---

projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.spec.ts
projects/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.ts

- The call to `zoomScale()` in chart setter was unnecessary. Setting the scale min/max is sufficient to set the initial zoom range. The chart will automatically zoom to those bounds on the first update.
- Ran patient app with Logica Open environment patient id: 31059
- Reloaded the page multiple times, switched to chart tab before/during/after loading data and checked initial zoom range.

Fix error: Cannot read properties of undefined

---

projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/home-measurement-summary.service.ts
projects/ngx-charts-on-fhir/src/lib/fhir-chart-summary/statistics.service.ts

- Fixed reference range tooltip issue for home measurement.
- Add check for checking in dataset label `(Home)` is present or not.
- If present then split it and pass it to the function.
Tested using run all `charts-on-fhir` apps locally.

RT-707-reference-range-tooltip-home-measurements

---

.github/workflows/pull-request.yml
libs/ngx-charts-on-fhir/package.json
libs/ngx-charts-on-fhir/project.json
libs/ngx-charts-on-fhir/test-npm-package.sh

- Adds a shell script for testing `npm pack` and `npm install` of the library into a new angular app
- Adds "test-npm-package" nx target for the library
- Adds "test-npm-package" job in the pull-request workflow
- Fixes some missing peer dependencies in library's package.json
- Ran the script using nx. 
- Verified that the `npm install` command fails when there are missing peer dependencies and succeeds when dependencies are fixed
- Verified that the angular app build succeeds
- Tested github workflow in this PR

NPM package integration test

---

.husky/pre-commit
.lintstagedrc.json
package-lock.json
package.json

- Adds a pre-commit hook (using [husky](https://typicode.github.io/husky/)) to auto-format staged files (using [lint-staged](https://github.com/okonet/lint-staged) and prettier)
- Committed a change with formatting errors and checked that formatting was corrected

Pre-commit hook for code formatting

---

libs/ngx-charts-on-fhir/src/lib/range-selector/range-selector.component.spec.ts
libs/ngx-charts-on-fhir/src/lib/range-selector/range-selector.component.ts

- updated code for range selector buttons to use today as the end date.
- updated test cases.
-Tested it by launching showcase, Cardiovascular Health, and cardio-patient locally.
-Ran unit test locally.

RT-723-Range-selector-buttons-should-use-today-as-end-date

---

libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.ts

In `FhirChartConfigurationService`  change the onZoomStart and onPanStart callbacks to onZoomComplete and onPanComplete callbacks.
Tested using run all `charts-on-fhir` locally.

RT-742-End date resets to previous value when changing layer options

---

libs/ngx-charts-on-fhir/src/lib/fhir-chart/scale-stack-divider-plugin.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart/scale-stack-divider-plugin.ts

- updated scaleStackDividerPlugin to use clearRect() instead of drawing a white line
- ran showcase app locally and set a non-white background color using chrome devtools

ScaleStackDivider assumes a white background

---

apps/cardiovascular-health/src/app/app.component.ts
libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.ts

-Updated data-layer-manger service to hide glucose by default.
-Now glucose is hidden by default if we click on the glucose checkbox it will display.
-Tested by launching cardiovascular-health, cardio-patient, and showcase locally.
-Ran unit test locally.

RT-739-Hide-Glucose-by-default

---

apps/cardiovascular-health/src/app/app.component.html
apps/cardiovascular-health/src/app/app.component.scss
apps/cardiovascular-patient-app/src/app/app.component.scss
apps/cardiovascular-patient-app/src/app/app.component.ts
apps/documentation/src/app/pages/components/chart-summary/demo/chart-summary-demo.component.html
apps/documentation/src/app/pages/components/chart-summary/demo/chart-summary-demo.css
apps/documentation/src/app/pages/components/chart-summary/index.md
apps/showcase/src/app/app.component.html
apps/showcase/src/app/app.component.scss
libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.ts
libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer.ts
libs/ngx-charts-on-fhir/src/lib/dynamic-table/dynamic-table.component.css
libs/ngx-charts-on-fhir/src/lib/dynamic-table/dynamic-table.component.html
libs/ngx-charts-on-fhir/src/lib/dynamic-table/dynamic-table.component.spec.ts
libs/ngx-charts-on-fhir/src/lib/dynamic-table/dynamic-table.component.ts
libs/ngx-charts-on-fhir/src/lib/dynamic-table/dynamic-table.module.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart-summary/fhir-chart-summary-card/fhir-chart-summary-card.component.css
libs/ngx-charts-on-fhir/src/lib/fhir-chart-summary/fhir-chart-summary-card/fhir-chart-summary-card.component.html
libs/ngx-charts-on-fhir/src/lib/fhir-chart-summary/fhir-chart-summary-card/fhir-chart-summary-card.component.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart-summary/fhir-chart-summary-card/fhir-chart-summary-card.component.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart-summary/fhir-chart-summary.module.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart-summary/fhir-chart-summary/fhir-chart-summary.component.css
libs/ngx-charts-on-fhir/src/lib/fhir-chart-summary/fhir-chart-summary/fhir-chart-summary.component.html
libs/ngx-charts-on-fhir/src/lib/fhir-chart-summary/fhir-chart-summary/fhir-chart-summary.component.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart-summary/fhir-chart-summary/fhir-chart-summary.component.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart-summary/statistics.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-lifecycle.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-lifecycle.service.ts

- added `autoAlign` input to `fhir-chart-summary` component, which will align each summary card with the corresponding chart.
- Summary cards can be expanded to full size by clicking on them.
- `dynamic-table` component now uses a basic CSS grid instead of MatTable. Row height scales proportionally so more content can fit into a smaller area.
- Re-ordered the rows returned by `StatisticsService` so the most important things are at the top.
- Added `FhirChartLifecycleService` that registers a chart.js plugin and exposes Observables for chart lifecycle events
- Ran all apps and tested summary cards at different window sizes
- Tested app functionality with card expanded
- Tested both horizontal and vertical layout in patient app

Responsive summary cards with no scrolling

---

Dockerfile

- Update `RUN npm ci` to `RUN npm ci --ignore-script` in Dockerfile.
- Rebuild and keep package scripts manually. (RUN npm rebuild @parcel/watcher nice-napi nx esbuild @swc/core).
Tested using run `Dockerfile` locally.

RT-733-ignore-scripts

---

libs/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/simple-medication-mapper.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/simple-medication-mapper.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.ts

- split y-axis labels into two lines to improve readability on small screens
- Ran cardio app, resized browser window and checked y-axis labels.

Split y-axis labels into two lines

---

apps/cardiovascular-health/src/app/app.component.ts
apps/cardiovascular-health/src/app/datasets/observations.json
apps/cardiovascular-health/src/app/datasets/observations.service.ts
apps/cardiovascular-health/src/app/providers/mapper-providers.ts
libs/ngx-charts-on-fhir/src/index.ts
libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer-color.service.ts
libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart-summary/statistics.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart-summary/statistics.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/fhir-code.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/fhir-code.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/simple-medication-mapper.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/simple-medication-mapper.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/blood-pressure-mapper.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/blood-pressure-mapper.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.ts
tsconfig.base.json

- Added `FhirCodeService`, which is responsible for returning the name of a CodeableConcept
- The default implementation simply returns `code.text`
- Built-in mappers now call `FhirCodeService.getName()` instead of using `code.text`
- Cardiovascular-health app now provides a custom FhirCodeService that replaces some of the names with ones that are shorter and more consistent
- Added some utility functions for comparing FHIR codes
- Changed reference range annotation matching code so it uses the new `chartsOnFhir.referenceRangeAnnotation` property on the dataset object instead of using the dataset label. Now the annotations will be matched correctly after customizing the dataset labels.
- Rewrote `BloodPressureMapper` so it passes a modified resource to the `ComponentObservationMapper` …

Customize layer names

---

libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.ts

This PR fixes a bug with lines not getting hidden when the dataset is unchecked in dataset-list component
Changes to DataLayerManagerService:
- Disable `autoEnable` when `update()` changes `dataset.hidden` or `layer.enabled`
- Disable `autoSelect` and select/remove layer when `update()` changes `layer.selected`
- Ran cardio app, checked/unchecked datasets and layers from options panel and made sure the chart updates correctly.
- Wrote some more unit tests

Disable autoEnable and autoSelect on layer update

---

libs/ngx-charts-on-fhir/src/lib/fhir-chart-summary/medication-summary.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart-summary/medication-summary.service.ts

In the medication summary card change the column label `Date Written` to `Last Written`.
Calculate the `First Written` Date based on `authoredOn` and display it in the medication summary card.
Update Test cases according to changes.
Tested using run showcase and cardio-health-app locally.

RT-736-Medication-summary-card-first-written-date

---

apps/cardiovascular-health/src/app/datasets/observations.service.ts
apps/documentation/src/app/pages/getting-started/retrieving-data/index.md
apps/showcase/src/app/datasets/observations.service.ts
libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer-merge.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-data/fhir-data.service.ts

- Sort FHIR Observation queries in reverse chronological order in all apps so most recent data is loaded first
- When merging new data into a layer, sort in reverse chronological order to avoid shuffling data points animation
- In cardio app, update chart after smaller batches of points to smooth out animations while loading data
- Use quicker default animations so everything feels a bit snappier.
- Ran cardio and showcase apps and watched the data load.

Smooth animations while data is loading

---

libs/ngx-charts-on-fhir/src/lib/data-layer-list/annotation-list/annotation-list.component.ts
libs/ngx-charts-on-fhir/src/lib/data-layer-list/annotation-options/annotation-options.component.ts
libs/ngx-charts-on-fhir/src/lib/data-layer-list/data-layer-options/data-layer-options.component.ts
libs/ngx-charts-on-fhir/src/lib/data-layer-list/dataset-list/dataset-list.component.ts
libs/ngx-charts-on-fhir/src/lib/data-layer-list/dataset-options/dataset-options.component.ts
libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.ts
libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer-merge.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer-merge.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart-legend/fhir-chart-tags-legend/fhir-chart-tags.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.ts

Fixes an issue when importing charts-on-fhir library in a project that uses Jest for unit tests.
- Ran showcase app and did a quick regression test.

Fix TypeError for immer default import

---

libs/ngx-charts-on-fhir/test-npm-package.Dockerfile
libs/ngx-charts-on-fhir/test-npm-package.sh

- test-npm-package script was using the wrong angular version because jq was not installed in docker image
- install angular material in test-npm-package script so it works with angular 15
- `nx run ngx-charts-on-fhir:test-npm-package`
- verified angular version in script output

Fix test-npm-package script

---

libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/duration-medication-mapper.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/simple-medication-mapper.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.ts

- Adds the raw FHIR resource as a property on each data point, so apps can work with the raw data (e.g. to display additional information) without maintaining their own state.
- Ran cardio app and did a quick regression test
- Temporarily added onClick handler that logged raw resources to console

Include resource object on chart data points

---

libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.ts

- Fixes a bug where `FhirChartConfigurationService` retains old data points that have been removed from the dataset.
- Added unit test that failed without the fix and passes with the fix
- Ran cardio app and watched the chart while loading data to make sure data points are added properly

Bugfix: Chart configuration service retains old data points

---

libs/ngx-charts-on-fhir/src/lib/timeline-range-selector/timeline-range-selector.component.css
libs/ngx-charts-on-fhir/src/lib/timeline-range-selector/timeline-range-selector.component.html
libs/ngx-charts-on-fhir/src/lib/timeline-range-selector/timeline-range-selector.component.spec.ts
libs/ngx-charts-on-fhir/src/lib/timeline-range-selector/timeline-range-selector.component.ts
libs/ngx-charts-on-fhir/src/lib/timeline-range-selector/timeline-range-selector.module.ts

- Use Material range selector instead of two date selectors
- Added alternate date range selector in dropdown menu
- Added alternate toggle buttons in dropdown menu
- Use CSS container queries to switch between alternative controls
- Ran cardio, showcase, and documentation apps
- Tested responsiveness when resized browser window, expanded sidebar
- Tested entering dates manually and via calendar in both alternatives
- Tested that graph updates correctly in all cases
- Tested switching between range presets with button toggles and dropdown menu

Responsive range selector

---

libs/ngx-charts-on-fhir/src/lib/fhir-chart-summary/fhir-chart-summary/fhir-chart-summary.component.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart-summary/fhir-chart-summary/fhir-chart-summary.component.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.ts

*  The chart should not show vertical lines for “1 month ago” and “2 months ago” by default when there is no summary component.
* The summary component should be responsible for adding these annotations.
* Tested locally by running showcase, cardio-patient, and cardio-health app
* Run unit test cases

RT-890:Hide summary range lines

---

libs/ngx-charts-on-fhir/package.json
libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.ts

* For error we are disabling a loading. so it will show an error message not to continue loading.
* Tested for all charts on fhir app
* Run a unit test on local.

Rt 895 graph shows endless loading animation after request error

---

apps/showcase/src/app/app.component.html
libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.html
libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.ts

- Modify the fhir-chart component to accept a customEmptyMessage input of type TemplateRef.
- Update the component's template to use the customEmptyMessage input when provided, otherwise use a default message.
- In the showcase app, set the customEmptyMessage input to "No data layers are selected" using a TemplateRef containing this message.
- Tested locally using run all charts-on-fhir apps.

RT-907-(charts-on-fhir) Empty message does not make sense when user cannot select layers

---

libs/ngx-charts-on-fhir/package.json
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/blood-pressure-mapper.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.ts

- Adds a layerName parameter to Observation mappers
- This makes it easier for custom mappers to change the layer name and scale label when calling the base mapper.
- Wrote a custom mapper that uses the layerName parameter (not committed)
- Ran showcase app and verified that custom name shows up in layer list, chart label, and summary card

Customize layer name

---

libs/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/simple-medication-mapper.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/simple-medication-mapper.service.ts

- Added the custom plugin for simpleMedicationMapper
- Removed the annotations 
- Added the unit test cases for simpleMedicationMapper
- Tested by launching the charts-on-fhir showcase app, and verified labels are showing as expected.
-  Also tested by using pack package of charts-on-fhir in the sapphire. 
- Verifed by launching hypertension and dementia app locally.

RT-1116: (charts-on-fhir) medication graph label cut off

---

libs/ngx-charts-on-fhir/package.json
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/fhir-mapper-options.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/reference-range.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/reference-range.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.ts

- Observation mappers now create line annotations when the reference range includes only a high value or only a low value.
- Refactored reference range annotation code into a ReferenceRangeService
- This does not change the statistics service, so summary cards will not show "Out of Range" calculation for single-valued reference ranges.
- Temporarily commented out high/low value in BloodPressureMapper and checked the annotations on the chart.

Single value reference range

---

package-lock.json

- Fixed babel vulnerability cve 2023-45133 by running `npm audit fix`
- Ran apps on local.
- Ran unit test cases on local.

babel vulnerability cve 2023-45133

---

libs/ngx-charts-on-fhir/package.json
libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer-color.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer-color.service.ts

- Fixes a bug in `DataLayerColorService` where `chooseColorsFromPalette` would override the callback function for scriptable options (`borderColor`, `backgroundColor`, `pointBorderColor` or `pointBackgroundColor`)
- Fixed descriptions of some other `DataLayerColorService` unit tests 
- Wrote unit tests
- Regression tested showcase and cardio app to make sure colors still get set correctly

fixed DataLayerColorService overrides callback functions

---

libs/ngx-charts-on-fhir/package.json
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/fhir-code.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/simple-medication-mapper.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.ts

- Adds a `resource` param to `FhirCodeService.getName()`
- This allows a custom implementation to use other resource properties (e.g. extensions) to determine the name
- Ran unit tests

Add resource param to FhirCodeService

---

libs/ngx-charts-on-fhir/package.json
libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/data-layer/data-layer-manager.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.css
libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.html

- Updated the dataLayerService to continue loading data from the other services when one of services throws an error while retrieving data
- Tested by intentionally failing a service call and launching the charts-on-fhir showcase app locally.

Handled the dataLayerService to continue loading data from the other services when one of service the service fails

---

nginx.conf

- Added log_format to enable json logging for the below services.
- showcase-web
- cardio-patient-web		
- cardio-web
- Tested by running the application locally and checked container logs.

OT-1151: Configure json logging for showcase,cardio and cardio-patient services

---

libs/ngx-charts-on-fhir/package.json
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/simple-observation-mapper.service.ts

Used category.code for group observations using category
Created two observations with different category.display and reproduce an issue on the local 
It was tested by the same observations after being fixed.
- [X ] I have added a link to this PR in the Jira issue
- [X ] I have described how this was tested
- [X ] I have updated unit tests
- [X ] I have run unit tests locally

RT-1327:(charts-on-fhir) Observation mapper creates multiple layers

---

libs/ngx-charts-on-fhir/package.json
libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart.component.ts

- Changed the order in which plugins are registered so annotations will be drawn after scale dividers
- Ran showcase app with mock fhir server and checked that encounter labels are not cut off when they overlap the divider

Rt 1322 encounter labels are drawn behind

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
libs/ngx-charts-on-fhir/package.json

Updated  actions/checkout@v3, actions/setup-node@v3. to actions/checkout@v4, actions/setup-node@v4
actions/checkout@v4, actions/setup-node@v4 use a node 20, 
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-node@v3. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
Created a PR and tested for Pull request action, I have also updated a release action
- [X ] I have added a link to this PR in the Jira issue
- [X ] I have described how this was tested

RT-1125:(charts-on-fhir) Node.js 16 actions are deprecated

---

libs/ngx-charts-on-fhir/package.json
libs/ngx-charts-on-fhir/src/lib/fhir-chart/fhir-chart-configuration.service.ts

Updated computeBounds function in FhirChartConfigurationService to support line annotations, having a value property instead of yMin and yMax.
Tested by launching showcase locally with different values off BPs
##Screenshot

Enhance annotation value extraction in computeBounds function

---

apps/cardio/src/app/app.component.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/observation/component-observation-mapper.service.ts
libs/ngx-charts-on-fhir/src/lib/patient-browser/patient.service.ts
package-lock.json
package.json

-  Updated **chartjs-plugin-annotation** to the latest version **3.1.0** to be compatible with "chart.js": "^4.3.3",
- Tested by running cardio, cardio-patients, showcase, and documentation app locally with mock data.
- Tested by running unit tests for all apps.

Update chartjs-plugin-annotation to version 3.1.0

---

libs/ngx-charts-on-fhir/package.json
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/duration-medication-mapper.service.spec.ts
libs/ngx-charts-on-fhir/src/lib/fhir-mappers/medication-request/duration-medication-mapper.service.ts

- Fixed MedicationDurationMapper so timing codes are not case sensitive
- Added missing timing code `WK`
- Added unit tests to cover uppercase timing codes
- Ran unit tests locally

Fixed timing codes used in medication duration calculation

---

libs/ngx-charts-on-fhir/package.json
libs/ngx-charts-on-fhir/src/lib/timeline-range-selector/timeline-range-selector.component.spec.ts
libs/ngx-charts-on-fhir/src/lib/timeline-range-selector/timeline-range-selector.component.ts

- Set max date to end of day when converting range strings in TimelineRangeSelector
- Tested locally with mock data.
- Tested by running unit tests.

Set max date to end of day when converting range strings in TimelineRangeSelector

---

libs/ngx-charts-on-fhir/package.json
libs/ngx-charts-on-fhir/src/lib/timeline-range-selector/timeline-range-selector.component.spec.ts
libs/ngx-charts-on-fhir/src/lib/timeline-range-selector/timeline-range-selector.component.ts

Refactor the dateChange method to use setTimeout for better timing control
Tested by launching the showcase app with mock data
Verified by choosing a custom range using the calendar control.
##Screenshot

RT-2081: Timeline range selector custom end date
